# scipy & numpy 的用法

## map 函数

在 `numpy` 中并未提供 map 方法，而是使用 vectorize 方法来代替。

现需要实现如下功能，有一个 2D 的数组（shape is (m, 1)），其中元素的值为 {0 | 1 | 2 | 3} 中的一个，即有4种标签，请将这个 2D 数组转换为 shape is (m, 4)，其中元素的转换规则为：
- 0: 转换为 [1, 0, 0, 0]
- 1: 转换为 [0, 1, 0, 0]
- 2: 转换为 [0, 0, 1, 0]
- 3: 转换为 [0, 0, 0, 1]

In [2]:
import numpy as np

In [4]:
def my_map(a, b):
    """
    a -- element in array
    b -- array
    
    # b is array, a is scalar
    # b == a 返回一个逻辑数组
    # 逻辑数组中每个元素的取值范围是 {True | False}
    # b == a 操作的意思是，用数组 b 中的每个元素与 a 比较
    # 如果相等则返回 True 否则返回 False
    # 比如：b = [0, 3, 3, 2, 1], a = 3, 则 b == a 返回的逻辑数组为
    # [False, True, True, False, False]
    """
    return b == a

# test
vfunc = np.vectorize(my_map)
a = 3
b = np.array([0,1,2,3])
c = vfunc(a, b)
c

array([False, False, False,  True])

In [7]:
# original array
X = np.random.randint(4, size=(5, 1))
# apply array
labels = np.arange(4)
# vectorize function
vfunc = np.vectorize(my_map)
r = vfunc(X, labels)

print(f'原始数组\n {X}')
print(f'map后的数组\n {r}')

原始数组
 [[0]
 [0]
 [3]
 [3]
 [1]]
map后的数组
 [[ True False False False]
 [ True False False False]
 [False False False  True]
 [False False False  True]
 [False  True False False]]


上面使用 vectorize 函数去实现，但有更简单的方法去实现，具体见下

In [8]:
# original array
X = np.random.randint(4, size=(5, 1))
# apply array
labels = np.arange(4)
#
r = X == labels

print(f'原始数组\n {X}')
print(f'map后的数组\n {r}')

原始数组
 [[1]
 [3]
 [0]
 [0]
 [3]]
map后的数组
 [[False  True False False]
 [False False False  True]
 [ True False False False]
 [ True False False False]
 [False False False  True]]
