In [78]:
import os
import pandas as pd
import numpy as np

x = os.listdir('./datas/ORL')
df = pd.DataFrame(x,columns=['file_name'])
df

file_name
0     s10_1.bmp
1    s10_10.bmp
2     s10_2.bmp
3     s10_3.bmp
4     s10_4.bmp
..          ...
395    s9_5.bmp
396    s9_6.bmp
397    s9_7.bmp
398    s9_8.bmp
399    s9_9.bmp

[400 rows x 1 columns]

In [40]:
df['file_group_name'] = df.file_name.str.extract(r'(.*)(_)')[0]
df

file_name file_group_name
0     s10_1.bmp             s10
1    s10_10.bmp             s10
2     s10_2.bmp             s10
3     s10_3.bmp             s10
4     s10_4.bmp             s10
..          ...             ...
395    s9_5.bmp              s9
396    s9_6.bmp              s9
397    s9_7.bmp              s9
398    s9_8.bmp              s9
399    s9_9.bmp              s9

[400 rows x 2 columns]

In [75]:
df['file_group_name'] = df.file_name.str.extract(r'(.*)(_)')[0]
grouped = df.groupby(['file_group_name'])
k=0.7
for v in grouped.groups.values():
    data = df['file_name'][v]
    train = data.sample(frac=k)
    test = data.drop(train.index)
    print(f'train is {train.values}')
    print(f'test is {test}')
    print(f'*'*15)

train is ['s1_1.bmp' 's1_6.bmp' 's1_5.bmp' 's1_8.bmp' 's1_7.bmp' 's1_9.bmp'
 's1_2.bmp']
test is 101    s1_10.bmp
103     s1_3.bmp
104     s1_4.bmp
Name: file_name, dtype: object
***************
train is ['s10_3.bmp' 's10_4.bmp' 's10_5.bmp' 's10_6.bmp' 's10_1.bmp' 's10_2.bmp'
 's10_10.bmp']
test is 7    s10_7.bmp
8    s10_8.bmp
9    s10_9.bmp
Name: file_name, dtype: object
***************
train is ['s11_5.bmp' 's11_2.bmp' 's11_8.bmp' 's11_10.bmp' 's11_3.bmp' 's11_1.bmp'
 's11_9.bmp']
test is 14    s11_4.bmp
16    s11_6.bmp
17    s11_7.bmp
Name: file_name, dtype: object
***************
train is ['s12_3.bmp' 's12_7.bmp' 's12_8.bmp' 's12_1.bmp' 's12_6.bmp' 's12_2.bmp'
 's12_4.bmp']
test is 21    s12_10.bmp
25     s12_5.bmp
29     s12_9.bmp
Name: file_name, dtype: object
***************
train is ['s13_8.bmp' 's13_4.bmp' 's13_5.bmp' 's13_1.bmp' 's13_3.bmp' 's13_10.bmp'
 's13_9.bmp']
test is 32    s13_2.bmp
36    s13_6.bmp
37    s13_7.bmp
Name: file_name, dtype: object
***************
train 

In [60]:
x = df.file_name[df.groupby(['file_group_name']).groups['s10']].sample(frac=0.7)
x

7    s10_7.bmp
4    s10_4.bmp
0    s10_1.bmp
3    s10_3.bmp
2    s10_2.bmp
9    s10_9.bmp
5    s10_5.bmp
Name: file_name, dtype: object

In [61]:
y = df.file_name[df.groupby(['file_group_name']).groups['s10']].drop(x.index)
y

1    s10_10.bmp
6     s10_6.bmp
8     s10_8.bmp
Name: file_name, dtype: object

In [81]:
x = np.zeros((2,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
x.flatten().reshape(1, -1).shape

(1, 10)

In [89]:
path='../datas/ORL'
print(os.path.join('..', 'datas', 'ORL', 's1_.dmp'))

..\datas\ORL\s1_.dmp


In [125]:
x = np.zeros((1,5))
x = np.concatenate((x, np.arange(5).reshape(1,5)))
x = np.concatenate((x, np.arange(5).reshape(1,5)))
x[1:,:]

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [129]:
x = np.array([])
x = np.append(x, 1)
x = np.append(x, 2)
x

array([1., 2.])

In [138]:
import re
s = 's10_1.bmp'
re.sub('_.*', '', s)

's10'