In [3]:
import numpy as np

In [7]:
x = np.random.randint(-5, 10, (5, 3))
print(f'原始矩阵{x.shape}：')
print(x)
print('='*20)

X = x.T
print(f'原始矩阵的转置矩阵{X.shape}：')
print(X)
print('='*20)

mu = X.mean(axis=1)[:, None]
print(f'转置矩阵的按行平均值{mu.shape}：')
print(mu)
print('='*20)

A = X - mu
print(f'转置矩阵的按行进行均值零化{A.shape}：')
print(A)
print('='*20)

C = (A @ A.T) / x.shape[0]
print(f'协方差矩阵{C.shape}：')
print(C)
print('='*20)

D, V = np.linalg.eig(C)
idx = D.argsort()[::-1]
D = D[idx]
V = V[:, idx]
print(f'协方差矩阵的特征值：{D}')
print(f'协方差矩阵的特征向量{V.shape}：')
print(V)
print('='*20)

P = V.T
print(f'P is {P.shape}：')
print(P)
print('='*20)

print(f'协方差对角矩阵 = P @ C @ P.T')
print(P @ C @ P.T)
print('='*20)

原始矩阵(5, 3)：
[[-5  3 -2]
 [ 4 -3  2]
 [ 5  6 -4]
 [ 7  8  3]
 [-4 -5  3]]
原始矩阵的转置矩阵(3, 5)：
[[-5  4  5  7 -4]
 [ 3 -3  6  8 -5]
 [-2  2 -4  3  3]]
转置矩阵的按行平均值(3, 1)：
[[1.4]
 [1.8]
 [0.4]]
转置矩阵的按行进行均值零化(3, 5)：
[[-6.4  2.6  3.6  5.6 -5.4]
 [ 1.2 -4.8  4.2  6.2 -6.8]
 [-2.4  1.6 -4.4  2.6  2.6]]
协方差矩阵(3, 3)：
[[24.24 13.28  0.84]
 [13.28 25.36 -6.12]
 [ 0.84 -6.12  8.24]]
协方差矩阵的特征值：[38.59096111 14.77799262  4.47104627]
协方差矩阵的特征向量(3, 3)：
[[-0.66943795 -0.65915454 -0.34259032]
 [-0.73158354  0.50489937  0.45810715]
 [ 0.12898977 -0.55730775  0.8202254 ]]
P is (3, 3)：
[[-0.66943795 -0.73158354  0.12898977]
 [-0.65915454  0.50489937 -0.55730775]
 [-0.34259032  0.45810715  0.8202254 ]]
协方差对角矩阵 = P @ C @ P.T
[[ 3.85909611e+01  1.12795218e-15  2.00573789e-15]
 [ 2.48821379e-15  1.47779926e+01 -7.98106851e-16]
 [ 3.10527320e-15 -7.13155930e-17  4.47104627e+00]]
